---
title: Trophy
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: 
baseurl: ''
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 
description: 
url: ''
twitter_username: 
default_img: 
name: 
profile_img: 
profile: 
social:
  github: 
exclude:
- _screenshots
- Gemfile
- Gemfile.lock
- LICENSE.txt
- README.md
markdown: kramdown
permalink: "/:year/:month/:day/:title/"
sass:
  style: compressed
gems:
- jekyll-paginate
- jekyll-sitemap
- octopress-autoprefixer
